general {
    hide_cursor = true
    ignore_empty_input = true
    fail_timeout = 1800
}

animations {
    enabled = true

    bezier = smooth, 0.05, 0.9, 0.1, 1.0

    animation = fade, 1, 2.0, smooth
    animation = inputField, 1, 2.5, smooth
}

background {
    monitor =
    path = screenshot
    color = rgba(7, 16, 21, 1.0)

    blur_passes = 3
    blur_size = 8
    brightness = 0.45
    contrast = 0.95
    vibrancy = 0.15
    noise = 0.01
}

shape {
    monitor =
    size = 420, 230
    color = rgba(7, 16, 21, 0.38)

    rounding = 30
    border_size = 2
    border_color = rgba(30, 175, 196, 0.58)

    shadow_passes = 2
    shadow_size = 12
    shadow_color = rgba(0, 0, 0, 0.55)

    position = 0, 0
    halign = center
    valign = center
    zindex = 1
}

label {
    monitor =
    text = $TIME
    color = rgba(217, 213, 195, 1.0)

    font_size = 72
    font_family = JetBrainsMono Nerd Font

    shadow_passes = 2
    shadow_size = 4
    shadow_color = rgba(0, 0, 0, 0.75)

    position = 0, 58
    halign = center
    valign = center
    zindex = 2
}

label {
    monitor =
    text = locked
    color = rgba(140, 203, 210, 0.82)

    font_size = 14
    font_family = JetBrainsMono Nerd Font

    position = 0, 8
    halign = center
    valign = center
    zindex = 2
}

input-field {
    monitor =
    size = 300, 50

    position = 0, -58
    halign = center
    valign = center
    zindex = 2

    outline_thickness = 2
    rounding = 17

    outer_color = rgba(30, 175, 196, 0.8)
    inner_color = rgba(7, 16, 21, 0.7)
    font_color = rgba(217, 213, 195, 1.0)

    check_color = rgba(199, 167, 108, 0.95)
    fail_color = rgba(215, 111, 74, 0.95)
    capslock_color = rgba(215, 111, 74, 0.95)

    dots_size = 0.22
    dots_spacing = 0.18
    dots_center = true
    dots_rounding = -1

    fade_on_empty = false

    placeholder_text = <i>password</i>
    fail_text = <i>wrong password</i>

    font_family = JetBrainsMono Nerd Font

    shadow_passes = 2
    shadow_size = 6
    shadow_color = rgba(0, 0, 0, 0.5)
}
